### ISSUE TITLE
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by Gnyblast** [githubnemo/CompileDaemon#74] opened 2022-03-22 13:46 UTC
Error comes up on newer versions of go like; 1.7<

The below dependency file contains math/bits which is causing related issue;
https://cs.opensource.google/go/x/sys/+/master:unix/affinity_linux.go;l=10?q=math%2Fbits&sq=&ss=go%2Fx%2Fsys

```
github.com/githubnemo/CompileDaemon (download)
github.com/fatih/color (download)
github.com/mattn/go-colorable (download)
github.com/mattn/go-isatty (download)
Fetching https://golang.org/x/sys/unix?go-get=1
Parsing meta tags from https://golang.org/x/sys/unix?go-get=1 (status code 200)
get "golang.org/x/sys/unix": found meta tag main.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
golang.org/x/sys (download)
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
github.com/fsnotify/fsnotify (download)
github.com/radovskyb/watcher (download)
```

**Comment by githubnemo** [comment] 2022-06-06 02:17
Sorry, I cannot reproduce this - a fresh build with current dependencies (and go 1.18) runs smoothly. It seems to me that whatever was the issue got fixed in the mean time.

If the error persists, please feel free to re-open the issue.

**Closed by githubnemo** 2022-06-06 02:17 UTC

**Comment by Gnyblast** [comment] 2022-06-06 08:34
Hey there,

I think it was some how related to the go version. I solved it but cannot recall exactly how atm.
